from typing import Optional

from sqlalchemy import ForeignKey, Integer, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from plexpy.db.models import Base, auto_pk


class Notifier(Base):
    __tablename__ = 'notifiers'

    id: Mapped[int] = auto_pk()
    agent_id: Mapped[Optional[int]] = mapped_column(Integer)
    agent_name: Mapped[Optional[str]] = mapped_column(Text)
    agent_label: Mapped[Optional[str]] = mapped_column(Text)
    friendly_name: Mapped[Optional[str]] = mapped_column(Text)
    notifier_config: Mapped[Optional[str]] = mapped_column(Text)
    on_play: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_stop: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_pause: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_resume: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_change: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_buffer: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_error: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_intro: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_credits: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_commercial: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_watched: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_created: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_extdown: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_intdown: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_extup: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_intup: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_pmsupdate: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_concurrent: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_newdevice: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_plexpyupdate: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_plexpydbcorrupt: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_tokenexpired: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    on_play_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_stop_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_pause_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_resume_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_change_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_buffer_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_error_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_intro_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_credits_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_commercial_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_watched_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_created_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_extdown_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_intdown_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_extup_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_intup_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_pmsupdate_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_concurrent_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_newdevice_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_plexpyupdate_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_plexpydbcorrupt_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_tokenexpired_subject: Mapped[Optional[str]] = mapped_column(Text)
    on_play_body: Mapped[Optional[str]] = mapped_column(Text)
    on_stop_body: Mapped[Optional[str]] = mapped_column(Text)
    on_pause_body: Mapped[Optional[str]] = mapped_column(Text)
    on_resume_body: Mapped[Optional[str]] = mapped_column(Text)
    on_change_body: Mapped[Optional[str]] = mapped_column(Text)
    on_buffer_body: Mapped[Optional[str]] = mapped_column(Text)
    on_error_body: Mapped[Optional[str]] = mapped_column(Text)
    on_intro_body: Mapped[Optional[str]] = mapped_column(Text)
    on_credits_body: Mapped[Optional[str]] = mapped_column(Text)
    on_commercial_body: Mapped[Optional[str]] = mapped_column(Text)
    on_watched_body: Mapped[Optional[str]] = mapped_column(Text)
    on_created_body: Mapped[Optional[str]] = mapped_column(Text)
    on_extdown_body: Mapped[Optional[str]] = mapped_column(Text)
    on_intdown_body: Mapped[Optional[str]] = mapped_column(Text)
    on_extup_body: Mapped[Optional[str]] = mapped_column(Text)
    on_intup_body: Mapped[Optional[str]] = mapped_column(Text)
    on_pmsupdate_body: Mapped[Optional[str]] = mapped_column(Text)
    on_concurrent_body: Mapped[Optional[str]] = mapped_column(Text)
    on_newdevice_body: Mapped[Optional[str]] = mapped_column(Text)
    on_plexpyupdate_body: Mapped[Optional[str]] = mapped_column(Text)
    on_plexpydbcorrupt_body: Mapped[Optional[str]] = mapped_column(Text)
    on_tokenexpired_body: Mapped[Optional[str]] = mapped_column(Text)
    custom_conditions: Mapped[Optional[str]] = mapped_column(Text)
    custom_conditions_logic: Mapped[Optional[str]] = mapped_column(Text)


class NotifyLog(Base):
    __tablename__ = 'notify_log'

    id: Mapped[int] = auto_pk()
    timestamp: Mapped[Optional[int]] = mapped_column(Integer)
    session_key: Mapped[Optional[int]] = mapped_column(Integer)
    rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    parent_rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    grandparent_rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    user_id: Mapped[Optional[int]] = mapped_column(Integer)
    user: Mapped[Optional[str]] = mapped_column(Text)
    notifier_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey('notifiers.id', ondelete='SET NULL'),
    )
    agent_id: Mapped[Optional[int]] = mapped_column(Integer)
    agent_name: Mapped[Optional[str]] = mapped_column(Text)
    notify_action: Mapped[Optional[str]] = mapped_column(Text)
    subject_text: Mapped[Optional[str]] = mapped_column(Text)
    body_text: Mapped[Optional[str]] = mapped_column(Text)
    script_args: Mapped[Optional[str]] = mapped_column(Text)
    poster_url: Mapped[Optional[str]] = mapped_column(Text)
    success: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    tag: Mapped[Optional[str]] = mapped_column(Text)
