from typing import Optional

from sqlalchemy import Integer, Text, text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from plexpy.db.models import Base, auto_pk


class Session(Base):
    __tablename__ = 'sessions'

    id: Mapped[int] = auto_pk()
    session_key: Mapped[Optional[int]] = mapped_column(Integer)
    session_id: Mapped[Optional[str]] = mapped_column(Text)
    transcode_key: Mapped[Optional[str]] = mapped_column(Text)
    rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    section_id: Mapped[Optional[int]] = mapped_column(Integer)
    media_type: Mapped[Optional[str]] = mapped_column(Text)
    started: Mapped[Optional[int]] = mapped_column(Integer)
    stopped: Mapped[Optional[int]] = mapped_column(Integer)
    paused_counter: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    state: Mapped[Optional[str]] = mapped_column(Text)
    user_id: Mapped[Optional[int]] = mapped_column(Integer)
    user: Mapped[Optional[str]] = mapped_column(Text)
    friendly_name: Mapped[Optional[str]] = mapped_column(Text)
    ip_address: Mapped[Optional[str]] = mapped_column(Text)
    machine_id: Mapped[Optional[str]] = mapped_column(Text)
    bandwidth: Mapped[Optional[int]] = mapped_column(Integer)
    location: Mapped[Optional[str]] = mapped_column(Text)
    player: Mapped[Optional[str]] = mapped_column(Text)
    product: Mapped[Optional[str]] = mapped_column(Text)
    platform: Mapped[Optional[str]] = mapped_column(Text)
    title: Mapped[Optional[str]] = mapped_column(Text)
    parent_title: Mapped[Optional[str]] = mapped_column(Text)
    grandparent_title: Mapped[Optional[str]] = mapped_column(Text)
    original_title: Mapped[Optional[str]] = mapped_column(Text)
    full_title: Mapped[Optional[str]] = mapped_column(Text)
    media_index: Mapped[Optional[int]] = mapped_column(Integer)
    parent_media_index: Mapped[Optional[int]] = mapped_column(Integer)
    thumb: Mapped[Optional[str]] = mapped_column(Text)
    parent_thumb: Mapped[Optional[str]] = mapped_column(Text)
    grandparent_thumb: Mapped[Optional[str]] = mapped_column(Text)
    year: Mapped[Optional[int]] = mapped_column(Integer)
    parent_rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    grandparent_rating_key: Mapped[Optional[int]] = mapped_column(Integer)
    originally_available_at: Mapped[Optional[str]] = mapped_column(Text)
    added_at: Mapped[Optional[int]] = mapped_column(Integer)
    guid: Mapped[Optional[str]] = mapped_column(Text)
    view_offset: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    duration: Mapped[Optional[int]] = mapped_column(Integer)
    video_decision: Mapped[Optional[str]] = mapped_column(Text)
    audio_decision: Mapped[Optional[str]] = mapped_column(Text)
    transcode_decision: Mapped[Optional[str]] = mapped_column(Text)
    container: Mapped[Optional[str]] = mapped_column(Text)
    bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    width: Mapped[Optional[int]] = mapped_column(Integer)
    height: Mapped[Optional[int]] = mapped_column(Integer)
    video_codec: Mapped[Optional[str]] = mapped_column(Text)
    video_bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    video_resolution: Mapped[Optional[str]] = mapped_column(Text)
    video_width: Mapped[Optional[int]] = mapped_column(Integer)
    video_height: Mapped[Optional[int]] = mapped_column(Integer)
    video_framerate: Mapped[Optional[str]] = mapped_column(Text)
    video_scan_type: Mapped[Optional[str]] = mapped_column(Text)
    video_full_resolution: Mapped[Optional[str]] = mapped_column(Text)
    video_dynamic_range: Mapped[Optional[str]] = mapped_column(Text)
    aspect_ratio: Mapped[Optional[str]] = mapped_column(Text)
    audio_codec: Mapped[Optional[str]] = mapped_column(Text)
    audio_bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    audio_channels: Mapped[Optional[int]] = mapped_column(Integer)
    audio_language: Mapped[Optional[str]] = mapped_column(Text)
    audio_language_code: Mapped[Optional[str]] = mapped_column(Text)
    subtitle_codec: Mapped[Optional[str]] = mapped_column(Text)
    subtitle_forced: Mapped[Optional[int]] = mapped_column(Integer)
    subtitle_language: Mapped[Optional[str]] = mapped_column(Text)
    stream_bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    stream_video_resolution: Mapped[Optional[str]] = mapped_column(Text)
    quality_profile: Mapped[Optional[str]] = mapped_column(Text)
    stream_container_decision: Mapped[Optional[str]] = mapped_column(Text)
    stream_container: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_decision: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_codec: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    stream_video_width: Mapped[Optional[int]] = mapped_column(Integer)
    stream_video_height: Mapped[Optional[int]] = mapped_column(Integer)
    stream_video_framerate: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_scan_type: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_full_resolution: Mapped[Optional[str]] = mapped_column(Text)
    stream_video_dynamic_range: Mapped[Optional[str]] = mapped_column(Text)
    stream_audio_decision: Mapped[Optional[str]] = mapped_column(Text)
    stream_audio_codec: Mapped[Optional[str]] = mapped_column(Text)
    stream_audio_bitrate: Mapped[Optional[int]] = mapped_column(Integer)
    stream_audio_channels: Mapped[Optional[int]] = mapped_column(Integer)
    stream_audio_language: Mapped[Optional[str]] = mapped_column(Text)
    stream_audio_language_code: Mapped[Optional[str]] = mapped_column(Text)
    subtitles: Mapped[Optional[int]] = mapped_column(Integer)
    stream_subtitle_decision: Mapped[Optional[str]] = mapped_column(Text)
    stream_subtitle_codec: Mapped[Optional[str]] = mapped_column(Text)
    stream_subtitle_forced: Mapped[Optional[int]] = mapped_column(Integer)
    stream_subtitle_language: Mapped[Optional[str]] = mapped_column(Text)
    transcode_protocol: Mapped[Optional[str]] = mapped_column(Text)
    transcode_container: Mapped[Optional[str]] = mapped_column(Text)
    transcode_video_codec: Mapped[Optional[str]] = mapped_column(Text)
    transcode_audio_codec: Mapped[Optional[str]] = mapped_column(Text)
    transcode_audio_channels: Mapped[Optional[int]] = mapped_column(Integer)
    transcode_width: Mapped[Optional[int]] = mapped_column(Integer)
    transcode_height: Mapped[Optional[int]] = mapped_column(Integer)
    transcode_hw_decoding: Mapped[Optional[int]] = mapped_column(Integer)
    transcode_hw_encoding: Mapped[Optional[int]] = mapped_column(Integer)
    optimized_version: Mapped[Optional[int]] = mapped_column(Integer)
    optimized_version_profile: Mapped[Optional[str]] = mapped_column(Text)
    optimized_version_title: Mapped[Optional[str]] = mapped_column(Text)
    synced_version: Mapped[Optional[int]] = mapped_column(Integer)
    synced_version_profile: Mapped[Optional[str]] = mapped_column(Text)
    live: Mapped[Optional[int]] = mapped_column(Integer)
    live_uuid: Mapped[Optional[str]] = mapped_column(Text)
    channel_call_sign: Mapped[Optional[str]] = mapped_column(Text)
    channel_id: Mapped[Optional[str]] = mapped_column(Text)
    channel_identifier: Mapped[Optional[str]] = mapped_column(Text)
    channel_title: Mapped[Optional[str]] = mapped_column(Text)
    channel_thumb: Mapped[Optional[str]] = mapped_column(Text)
    channel_vcn: Mapped[Optional[str]] = mapped_column(Text)
    secure: Mapped[Optional[int]] = mapped_column(Integer)
    relayed: Mapped[Optional[int]] = mapped_column(Integer)
    buffer_count: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    buffer_last_triggered: Mapped[Optional[int]] = mapped_column(Integer)
    last_paused: Mapped[Optional[int]] = mapped_column(Integer)
    watched: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    intro: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    credits: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    commercial: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    marker: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    initial_stream: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('1'))
    write_attempts: Mapped[Optional[int]] = mapped_column(Integer, server_default=text('0'))
    raw_stream_info: Mapped[Optional[str]] = mapped_column(Text)
    rating_key_websocket: Mapped[Optional[str]] = mapped_column(Text)


class SessionContinued(Base):
    __tablename__ = 'sessions_continued'
    __table_args__ = (
        UniqueConstraint('user_id', 'machine_id', 'media_type', name='idx_sessions_continued'),
    )

    id: Mapped[int] = auto_pk()
    user_id: Mapped[Optional[int]] = mapped_column(Integer)
    machine_id: Mapped[Optional[str]] = mapped_column(Text)
    media_type: Mapped[Optional[str]] = mapped_column(Text)
    stopped: Mapped[Optional[int]] = mapped_column(Integer)
